name: "CocoChorales"
type: "audio"
callable: "datasets.audiofolder.AudioFolderDataset"
#path: "/u/25/molinee2/unix/datasets/MusicNet/train"
path: "/scratch/elec/t412-asp/audio_datasets/CocoChorales/cocochorales_full_v1_zipped/strings/train"

overfit: False
      
test:
   callable: "datasets.audiofolder_test.AudioFolderDatasetTest"
   #path: "/u/25/molinee2/unix/datasets/MusicNet/train"
   path: "/scratch/elec/t412-asp/audio_datasets/CocoChorales/cocochorales_full_v1_zipped/strings/test"
   stereo: False
   num_samples: 4
   batch_size: 1

