name: "CocoChorales"
type: "audio"
callable: "datasets.cocochorales.AudioFolderDataset"
#path: "/u/25/molinee2/unix/datasets/MusicNet/train"
path: "/scratch/elec/t412-asp/audio_datasets/CocoChorales/cocochorales_full_v1_zipped/woodwind/train"

overfit: False

prob_quartet: 0.25
prob_solo: 0.25
prob_duo: 0.25
prob_trio: 0.25
      
test:
   callable: "datasets.audiofolder_test.AudioFolderDatasetTest"
   #path: "/u/25/molinee2/unix/datasets/MusicNet/train"
   path: "/scratch/elec/t412-asp/audio_datasets/CocoChorales/cocochorales_full_v1_zipped/strings/test"
   stereo: False
   num_samples: 4
   batch_size: 1

