name: "musdb"
type: "audio"
callable: "datasets.audiofolder.AudioFolderDataset"
#path: "/u/25/molinee2/unix/datasets/MusicNet/train"
path: "/scratch/work/molinee2/datasets/musdb18hq/train"

overfit: False
      
test:
   callable: "datasets.audiofolder_test.AudioFolderDataset"
   #path: "/u/25/molinee2/unix/datasets/MusicNet/train"
   path: "/scratch/work/molinee2/datasets/musdb18hq/test"
   num_samples: 4
   batch_size: 1

